#
# Generated by the NeXT Project Builder.
#
# NOTE: Do NOT change this file -- Project Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = HelloWorld

PROJECTVERSION = 1.1
LANGUAGE = English

MFILES = HelloWorld_main.m

OTHERSRCS = Makefile


MAKEFILEDIR = /NextDeveloper/Makefiles/app
MAKEFILE = tool.make
INSTALLDIR = $(HOME)/bin
INSTALLFLAGS = -c -s -m 755
SOURCEMODE = 444

LIBS = -lFoundation_s
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)




-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
